---
name: Publish Release

on:
  workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        
        steps:
            - name: Get latest successful run ID for build workflow
              id: resolve_run
              uses: actions/github-script@v7
              with:
                script: |
                    const workflowName = `package-sabnzbd.yml`;
                    const runs = await github.rest.actions.listWorkflowRuns({
                                                                              owner: context.repo.owner,
                                                                              repo: context.repo.repo,
                                                                              workflow_id: workflowName,
                                                                              status: 'success',
                                                                              per_page: 1
                                                                          });
                    if (runs.data.workflow_runs.length === 0) {
                        core.setFailed(`No successful runs found for workflow: ${workflowName}`);
                    } else {
                        const latestRunId = runs.data.workflow_runs[0].id;
                        core.info(`Using latest successful run ID: ${latestRunId}`);
                        core.setOutput('run_id', latestRunId);
                    }

            - name: Download release artifact along with manifest
              uses: actions/download-artifact@v4
              with:
                name: SABnzbdPortableInstaller
                path: release
                run-id: ${{ steps.resolve_run.outputs.run_id }}

            - name: Parse release-manifest.json
              id: metadata
              shell: bash
              run: |
                manifest="release-manifest.json"
                version=$(jq -r .version "$manifest")
                build=$(jq -r .build "$manifest")
                tag=$(jq -r .tag "$manifest")
                artifact=$(jq -r .artifact "$manifest")
                echo "version=$version" >> $GITHUB_OUTPUT
                echo "build=$build" >> $GITHUB_OUTPUT
                echo "tag=$tag" >> $GITHUB_OUTPUT
                echo "artifact=$artifact" >> $GITHUB_OUTPUT

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ steps.metadata.outputs.tag }}
                release_name: Version  ${{ steps.metadata.outputs.version }}
                draft: false
                prerelease: false

            - name: Upload installer to release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ steps.metadata.outputs.tag }}
                name: ${{ steps.metadata.outputs.artifact }}
                files: |
                    ./release/SABnzbdPortable_*.paf.exe
                    ./release/release-manifest.json
